# Number of files to be generated for the server
test_files: 50

# Number of test cases to include per file (including edge cases)
test_cases:
  devel: 200
  prod: 200

semester: spring2013

problems:
  split:
    runners:
      - runner_vera.py

  travel:
    runners:
      - runner_andrew.py

  fitness:
    runners:
      - runner_andrew.py

  shaving:
    runners:
      - runner_doug.py
